### ISSUE TITLE
Links para os .md das apresentações no README

### ISSUE THREAD

**Issue by ItaloSa** [reactrecife/meetups#1]
Acredito que é mais intuitivo pra quem ta chegando agora na comunidade, acessar os README das talks a partir de um link no `README.md`. 

Algo do tipo:

## Talks
- [08/19 - Liferay](README-MEETUP-08-19-LIFERAY.md) 
- [11/19 - Inloco](README-MEETUP-11-19-INLOCO.md)

---

> code
```
## Talks
- [08/19 - Liferay](README-MEETUP-08-19-LIFERAY.md)
- [11/19 - Inloco](README-MEETUP-11-19-INLOCO.md)
```

**Comment by diegonvs** [comment]
Verdade Italo! Podes mandar um pull request alterando no nosso README?

**Comment by ItaloSa** [comment]
Sim! Farei isso em breve!
